# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e381017f1db196217a4427f56d745b2dd63380e660d1ff91323f09c6925874f22809d980cba4a25d7c4caf9750a52cee87f08696e6f8bc4e6598f75dff95006f

test:
  secret_key_base: 84cc18781ae26d825e48287ab52fc28e9af553c8910420cac1dfd3278de1bf32b4b44921b3dd09e0bd4ef160a85ca8a8a93da0d1cbe6cedee08441415d59f66b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
